leagueSchedule = {
	1: [
		{'homeSlot': 0, 'awaySlot': 19},
		{'homeSlot': 1, 'awaySlot': 18},
		{'homeSlot': 2, 'awaySlot': 17},
		{'homeSlot': 3, 'awaySlot': 16},
		{'homeSlot': 4, 'awaySlot': 15},
		{'homeSlot': 5, 'awaySlot': 14},
		{'homeSlot': 6, 'awaySlot': 13},
		{'homeSlot': 7, 'awaySlot': 12},
		{'homeSlot': 8, 'awaySlot': 11},
		{'homeSlot': 9, 'awaySlot': 10}
	],
	2: [
		{'homeSlot': 18, 'awaySlot': 0},
		{'homeSlot': 17, 'awaySlot': 19},
		{'homeSlot': 16, 'awaySlot': 1},
		{'homeSlot': 15, 'awaySlot': 2},
		{'homeSlot': 14, 'awaySlot': 3},
		{'homeSlot': 13, 'awaySlot': 4},
		{'homeSlot': 12, 'awaySlot': 5},
		{'homeSlot': 11, 'awaySlot': 6},
		{'homeSlot': 10, 'awaySlot': 7},
		{'homeSlot': 9, 'awaySlot': 8}
	],
	3: [
		{'homeSlot': 0, 'awaySlot': 17},
		{'homeSlot': 18, 'awaySlot': 16},
		{'homeSlot': 19, 'awaySlot': 15},
		{'homeSlot': 1, 'awaySlot': 14},
		{'homeSlot': 2, 'awaySlot': 13},
		{'homeSlot': 3, 'awaySlot': 12},
		{'homeSlot': 4, 'awaySlot': 11},
		{'homeSlot': 5, 'awaySlot': 10},
		{'homeSlot': 6, 'awaySlot': 9},
		{'homeSlot': 7, 'awaySlot': 8}
	],
	4: [
		{'homeSlot': 16, 'awaySlot': 0},
		{'homeSlot': 15, 'awaySlot': 17},
		{'homeSlot': 14, 'awaySlot': 18},
		{'homeSlot': 13, 'awaySlot': 19},
		{'homeSlot': 12, 'awaySlot': 1},
		{'homeSlot': 11, 'awaySlot': 2},
		{'homeSlot': 10, 'awaySlot': 3},
		{'homeSlot': 9, 'awaySlot': 4},
		{'homeSlot': 8, 'awaySlot': 5},
		{'homeSlot': 7, 'awaySlot': 6}
	],
	5: [
		{'homeSlot': 0, 'awaySlot': 15},
		{'homeSlot': 16, 'awaySlot': 14},
		{'homeSlot': 17, 'awaySlot': 13},
		{'homeSlot': 18, 'awaySlot': 12},
		{'homeSlot': 19, 'awaySlot': 11},
		{'homeSlot': 1, 'awaySlot': 10},
		{'homeSlot': 2, 'awaySlot': 9},
		{'homeSlot': 3, 'awaySlot': 8},
		{'homeSlot': 4, 'awaySlot': 7},
		{'homeSlot': 5, 'awaySlot': 6}
	],
	6: [
		{'homeSlot': 14, 'awaySlot': 0},
		{'homeSlot': 13, 'awaySlot': 15},
		{'homeSlot': 12, 'awaySlot': 16},
		{'homeSlot': 11, 'awaySlot': 17},
		{'homeSlot': 10, 'awaySlot': 18},
		{'homeSlot': 9, 'awaySlot': 19},
		{'homeSlot': 8, 'awaySlot': 1},
		{'homeSlot': 7, 'awaySlot': 2},
		{'homeSlot': 6, 'awaySlot': 3},
		{'homeSlot': 5, 'awaySlot': 4}
	],
	7: [
		{'homeSlot': 0, 'awaySlot': 13},
		{'homeSlot': 14, 'awaySlot': 12},
		{'homeSlot': 15, 'awaySlot': 11},
		{'homeSlot': 16, 'awaySlot': 10},
		{'homeSlot': 17, 'awaySlot': 9},
		{'homeSlot': 18, 'awaySlot': 8},
		{'homeSlot': 19, 'awaySlot': 7},
		{'homeSlot': 1, 'awaySlot': 6},
		{'homeSlot': 2, 'awaySlot': 5},
		{'homeSlot': 3, 'awaySlot': 4}
	],
	8: [
		{'homeSlot': 12, 'awaySlot': 0},
		{'homeSlot': 11, 'awaySlot': 13},
		{'homeSlot': 10, 'awaySlot': 14},
		{'homeSlot': 9, 'awaySlot': 15},
		{'homeSlot': 8, 'awaySlot': 16},
		{'homeSlot': 7, 'awaySlot': 17},
		{'homeSlot': 6, 'awaySlot': 18},
		{'homeSlot': 5, 'awaySlot': 19},
		{'homeSlot': 4, 'awaySlot': 1},
		{'homeSlot': 3, 'awaySlot': 2}
	],
	9: [
		{'homeSlot': 0, 'awaySlot': 11},
		{'homeSlot': 12, 'awaySlot': 10},
		{'homeSlot': 13, 'awaySlot': 9},
		{'homeSlot': 14, 'awaySlot': 8},
		{'homeSlot': 15, 'awaySlot': 7},
		{'homeSlot': 16, 'awaySlot': 6},
		{'homeSlot': 17, 'awaySlot': 5},
		{'homeSlot': 18, 'awaySlot': 4},
		{'homeSlot': 19, 'awaySlot': 3},
		{'homeSlot': 1, 'awaySlot': 2}
	],
	10: [
		{'homeSlot': 10, 'awaySlot': 0},
		{'homeSlot': 9, 'awaySlot': 11},
		{'homeSlot': 8, 'awaySlot': 12},
		{'homeSlot': 7, 'awaySlot': 13},
		{'homeSlot': 6, 'awaySlot': 14},
		{'homeSlot': 5, 'awaySlot': 15},
		{'homeSlot': 4, 'awaySlot': 16},
		{'homeSlot': 3, 'awaySlot': 17},
		{'homeSlot': 2, 'awaySlot': 18},
		{'homeSlot': 1, 'awaySlot': 19}
	],
	11: [
		{'homeSlot': 0, 'awaySlot': 9},
		{'homeSlot': 10, 'awaySlot': 8},
		{'homeSlot': 11, 'awaySlot': 7},
		{'homeSlot': 12, 'awaySlot': 6},
		{'homeSlot': 13, 'awaySlot': 5},
		{'homeSlot': 14, 'awaySlot': 4},
		{'homeSlot': 15, 'awaySlot': 3},
		{'homeSlot': 16, 'awaySlot': 2},
		{'homeSlot': 17, 'awaySlot': 1},
		{'homeSlot': 18, 'awaySlot': 19}
	],
	12: [
		{'homeSlot': 8, 'awaySlot': 0},
		{'homeSlot': 7, 'awaySlot': 9},
		{'homeSlot': 6, 'awaySlot': 10},
		{'homeSlot': 5, 'awaySlot': 11},
		{'homeSlot': 4, 'awaySlot': 12},
		{'homeSlot': 3, 'awaySlot': 13},
		{'homeSlot': 2, 'awaySlot': 14},
		{'homeSlot': 1, 'awaySlot': 15},
		{'homeSlot': 19, 'awaySlot': 16},
		{'homeSlot': 18, 'awaySlot': 17}
	],
	13: [
		{'homeSlot': 0, 'awaySlot': 7},
		{'homeSlot': 8, 'awaySlot': 6},
		{'homeSlot': 9, 'awaySlot': 5},
		{'homeSlot': 10, 'awaySlot': 4},
		{'homeSlot': 11, 'awaySlot': 3},
		{'homeSlot': 12, 'awaySlot': 2},
		{'homeSlot': 13, 'awaySlot': 1},
		{'homeSlot': 14, 'awaySlot': 19},
		{'homeSlot': 15, 'awaySlot': 18},
		{'homeSlot': 16, 'awaySlot': 17}
	],
	14: [
		{'homeSlot': 6, 'awaySlot': 0},
		{'homeSlot': 5, 'awaySlot': 7},
		{'homeSlot': 4, 'awaySlot': 8},
		{'homeSlot': 3, 'awaySlot': 9},
		{'homeSlot': 2, 'awaySlot': 10},
		{'homeSlot': 1, 'awaySlot': 11},
		{'homeSlot': 19, 'awaySlot': 12},
		{'homeSlot': 18, 'awaySlot': 13},
		{'homeSlot': 17, 'awaySlot': 14},
		{'homeSlot': 16, 'awaySlot': 15}
	],
	15: [
		{'homeSlot': 0, 'awaySlot': 5},
		{'homeSlot': 6, 'awaySlot': 4},
		{'homeSlot': 7, 'awaySlot': 3},
		{'homeSlot': 8, 'awaySlot': 2},
		{'homeSlot': 9, 'awaySlot': 1},
		{'homeSlot': 10, 'awaySlot': 19},
		{'homeSlot': 11, 'awaySlot': 18},
		{'homeSlot': 12, 'awaySlot': 17},
		{'homeSlot': 13, 'awaySlot': 16},
		{'homeSlot': 14, 'awaySlot': 15}
	],
	16: [
		{'homeSlot': 4, 'awaySlot': 0},
		{'homeSlot': 3, 'awaySlot': 5},
		{'homeSlot': 2, 'awaySlot': 6},
		{'homeSlot': 1, 'awaySlot': 7},
		{'homeSlot': 19, 'awaySlot': 8},
		{'homeSlot': 18, 'awaySlot': 9},
		{'homeSlot': 17, 'awaySlot': 10},
		{'homeSlot': 16, 'awaySlot': 11},
		{'homeSlot': 15, 'awaySlot': 12},
		{'homeSlot': 14, 'awaySlot': 13}
	],
	17: [
		{'homeSlot': 0, 'awaySlot': 3},
		{'homeSlot': 4, 'awaySlot': 2},
		{'homeSlot': 5, 'awaySlot': 1},
		{'homeSlot': 6, 'awaySlot': 19},
		{'homeSlot': 7, 'awaySlot': 18},
		{'homeSlot': 8, 'awaySlot': 17},
		{'homeSlot': 9, 'awaySlot': 16},
		{'homeSlot': 10, 'awaySlot': 15},
		{'homeSlot': 11, 'awaySlot': 14},
		{'homeSlot': 12, 'awaySlot': 13}
	],
	18: [
		{'homeSlot': 2, 'awaySlot': 0},
		{'homeSlot': 1, 'awaySlot': 3},
		{'homeSlot': 19, 'awaySlot': 4},
		{'homeSlot': 18, 'awaySlot': 5},
		{'homeSlot': 17, 'awaySlot': 6},
		{'homeSlot': 16, 'awaySlot': 7},
		{'homeSlot': 15, 'awaySlot': 8},
		{'homeSlot': 14, 'awaySlot': 9},
		{'homeSlot': 13, 'awaySlot': 10},
		{'homeSlot': 12, 'awaySlot': 11}
	],
	19: [
		{'homeSlot': 0, 'awaySlot': 1},
		{'homeSlot': 2, 'awaySlot': 19},
		{'homeSlot': 3, 'awaySlot': 18},
		{'homeSlot': 4, 'awaySlot': 17},
		{'homeSlot': 5, 'awaySlot': 16},
		{'homeSlot': 6, 'awaySlot': 15},
		{'homeSlot': 7, 'awaySlot': 14},
		{'homeSlot': 8, 'awaySlot': 13},
		{'homeSlot': 9, 'awaySlot': 12},
		{'homeSlot': 10, 'awaySlot': 11}
	],
	20: [
		{'homeSlot': 19, 'awaySlot': 0},
		{'homeSlot': 18, 'awaySlot': 1},
		{'homeSlot': 17, 'awaySlot': 2},
		{'homeSlot': 16, 'awaySlot': 3},
		{'homeSlot': 15, 'awaySlot': 4},
		{'homeSlot': 14, 'awaySlot': 5},
		{'homeSlot': 13, 'awaySlot': 6},
		{'homeSlot': 12, 'awaySlot': 7},
		{'homeSlot': 11, 'awaySlot': 8},
		{'homeSlot': 10, 'awaySlot': 9}
	],
	21: [
		{'homeSlot': 0, 'awaySlot': 18},
		{'homeSlot': 19, 'awaySlot': 17},
		{'homeSlot': 1, 'awaySlot': 16},
		{'homeSlot': 2, 'awaySlot': 15},
		{'homeSlot': 3, 'awaySlot': 14},
		{'homeSlot': 4, 'awaySlot': 13},
		{'homeSlot': 5, 'awaySlot': 12},
		{'homeSlot': 6, 'awaySlot': 11},
		{'homeSlot': 7, 'awaySlot': 10},
		{'homeSlot': 8, 'awaySlot': 9}
	],
	22: [
		{'homeSlot': 17, 'awaySlot': 0},
		{'homeSlot': 16, 'awaySlot': 18},
		{'homeSlot': 15, 'awaySlot': 19},
		{'homeSlot': 14, 'awaySlot': 1},
		{'homeSlot': 13, 'awaySlot': 2},
		{'homeSlot': 12, 'awaySlot': 3},
		{'homeSlot': 11, 'awaySlot': 4},
		{'homeSlot': 10, 'awaySlot': 5},
		{'homeSlot': 9, 'awaySlot': 6},
		{'homeSlot': 8, 'awaySlot': 7}
	],
	23: [
		{'homeSlot': 0, 'awaySlot': 16},
		{'homeSlot': 17, 'awaySlot': 15},
		{'homeSlot': 18, 'awaySlot': 14},
		{'homeSlot': 19, 'awaySlot': 13},
		{'homeSlot': 1, 'awaySlot': 12},
		{'homeSlot': 2, 'awaySlot': 11},
		{'homeSlot': 3, 'awaySlot': 10},
		{'homeSlot': 4, 'awaySlot': 9},
		{'homeSlot': 5, 'awaySlot': 8},
		{'homeSlot': 6, 'awaySlot': 7}
	],
	24: [
		{'homeSlot': 15, 'awaySlot': 0},
		{'homeSlot': 14, 'awaySlot': 16},
		{'homeSlot': 13, 'awaySlot': 17},
		{'homeSlot': 12, 'awaySlot': 18},
		{'homeSlot': 11, 'awaySlot': 19},
		{'homeSlot': 10, 'awaySlot': 1},
		{'homeSlot': 9, 'awaySlot': 2},
		{'homeSlot': 8, 'awaySlot': 3},
		{'homeSlot': 7, 'awaySlot': 4},
		{'homeSlot': 6, 'awaySlot': 5}
	],
	25: [
		{'homeSlot': 0, 'awaySlot': 14},
		{'homeSlot': 15, 'awaySlot': 13},
		{'homeSlot': 16, 'awaySlot': 12},
		{'homeSlot': 17, 'awaySlot': 11},
		{'homeSlot': 18, 'awaySlot': 10},
		{'homeSlot': 19, 'awaySlot': 9},
		{'homeSlot': 1, 'awaySlot': 8},
		{'homeSlot': 2, 'awaySlot': 7},
		{'homeSlot': 3, 'awaySlot': 6},
		{'homeSlot': 4, 'awaySlot': 5}
	],
	26: [
		{'homeSlot': 13, 'awaySlot': 0},
		{'homeSlot': 12, 'awaySlot': 14},
		{'homeSlot': 11, 'awaySlot': 15},
		{'homeSlot': 10, 'awaySlot': 16},
		{'homeSlot': 9, 'awaySlot': 17},
		{'homeSlot': 8, 'awaySlot': 18},
		{'homeSlot': 7, 'awaySlot': 19},
		{'homeSlot': 6, 'awaySlot': 1},
		{'homeSlot': 5, 'awaySlot': 2},
		{'homeSlot': 4, 'awaySlot': 3}
	],
	27: [
		{'homeSlot': 0, 'awaySlot': 12},
		{'homeSlot': 13, 'awaySlot': 11},
		{'homeSlot': 14, 'awaySlot': 10},
		{'homeSlot': 15, 'awaySlot': 9},
		{'homeSlot': 16, 'awaySlot': 8},
		{'homeSlot': 17, 'awaySlot': 7},
		{'homeSlot': 18, 'awaySlot': 6},
		{'homeSlot': 19, 'awaySlot': 5},
		{'homeSlot': 1, 'awaySlot': 4},
		{'homeSlot': 2, 'awaySlot': 3}
	],
	28: [
		{'homeSlot': 11, 'awaySlot': 0},
		{'homeSlot': 10, 'awaySlot': 12},
		{'homeSlot': 9, 'awaySlot': 13},
		{'homeSlot': 8, 'awaySlot': 14},
		{'homeSlot': 7, 'awaySlot': 15},
		{'homeSlot': 6, 'awaySlot': 16},
		{'homeSlot': 5, 'awaySlot': 17},
		{'homeSlot': 4, 'awaySlot': 18},
		{'homeSlot': 3, 'awaySlot': 19},
		{'homeSlot': 2, 'awaySlot': 1}
	],
	29: [
		{'homeSlot': 0, 'awaySlot': 10},
		{'homeSlot': 11, 'awaySlot': 9},
		{'homeSlot': 12, 'awaySlot': 8},
		{'homeSlot': 13, 'awaySlot': 7},
		{'homeSlot': 14, 'awaySlot': 6},
		{'homeSlot': 15, 'awaySlot': 5},
		{'homeSlot': 16, 'awaySlot': 4},
		{'homeSlot': 17, 'awaySlot': 3},
		{'homeSlot': 18, 'awaySlot': 2},
		{'homeSlot': 19, 'awaySlot': 1}
	],
	30: [
		{'homeSlot': 9, 'awaySlot': 0},
		{'homeSlot': 8, 'awaySlot': 10},
		{'homeSlot': 7, 'awaySlot': 11},
		{'homeSlot': 6, 'awaySlot': 12},
		{'homeSlot': 5, 'awaySlot': 13},
		{'homeSlot': 4, 'awaySlot': 14},
		{'homeSlot': 3, 'awaySlot': 15},
		{'homeSlot': 2, 'awaySlot': 16},
		{'homeSlot': 1, 'awaySlot': 17},
		{'homeSlot': 19, 'awaySlot': 18}
	],
	31: [
		{'homeSlot': 0, 'awaySlot': 8},
		{'homeSlot': 9, 'awaySlot': 7},
		{'homeSlot': 10, 'awaySlot': 6},
		{'homeSlot': 11, 'awaySlot': 5},
		{'homeSlot': 12, 'awaySlot': 4},
		{'homeSlot': 13, 'awaySlot': 3},
		{'homeSlot': 14, 'awaySlot': 2},
		{'homeSlot': 15, 'awaySlot': 1},
		{'homeSlot': 16, 'awaySlot': 19},
		{'homeSlot': 17, 'awaySlot': 18}
	],
	32: [
		{'homeSlot': 7, 'awaySlot': 0},
		{'homeSlot': 6, 'awaySlot': 8},
		{'homeSlot': 5, 'awaySlot': 9},
		{'homeSlot': 4, 'awaySlot': 10},
		{'homeSlot': 3, 'awaySlot': 11},
		{'homeSlot': 2, 'awaySlot': 12},
		{'homeSlot': 1, 'awaySlot': 13},
		{'homeSlot': 19, 'awaySlot': 14},
		{'homeSlot': 18, 'awaySlot': 15},
		{'homeSlot': 17, 'awaySlot': 16}
	],
	33: [
		{'homeSlot': 0, 'awaySlot': 6},
		{'homeSlot': 7, 'awaySlot': 5},
		{'homeSlot': 8, 'awaySlot': 4},
		{'homeSlot': 9, 'awaySlot': 3},
		{'homeSlot': 10, 'awaySlot': 2},
		{'homeSlot': 11, 'awaySlot': 1},
		{'homeSlot': 12, 'awaySlot': 19},
		{'homeSlot': 13, 'awaySlot': 18},
		{'homeSlot': 14, 'awaySlot': 17},
		{'homeSlot': 15, 'awaySlot': 16}
	],
	34: [
		{'homeSlot': 5, 'awaySlot': 0},
		{'homeSlot': 4, 'awaySlot': 6},
		{'homeSlot': 3, 'awaySlot': 7},
		{'homeSlot': 2, 'awaySlot': 8},
		{'homeSlot': 1, 'awaySlot': 9},
		{'homeSlot': 19, 'awaySlot': 10},
		{'homeSlot': 18, 'awaySlot': 11},
		{'homeSlot': 17, 'awaySlot': 12},
		{'homeSlot': 16, 'awaySlot': 13},
		{'homeSlot': 15, 'awaySlot': 14}
	],
	35: [
		{'homeSlot': 0, 'awaySlot': 4},
		{'homeSlot': 5, 'awaySlot': 3},
		{'homeSlot': 6, 'awaySlot': 2},
		{'homeSlot': 7, 'awaySlot': 1},
		{'homeSlot': 8, 'awaySlot': 19},
		{'homeSlot': 9, 'awaySlot': 18},
		{'homeSlot': 10, 'awaySlot': 17},
		{'homeSlot': 11, 'awaySlot': 16},
		{'homeSlot': 12, 'awaySlot': 15},
		{'homeSlot': 13, 'awaySlot': 14}
	],
	36: [
		{'homeSlot': 3, 'awaySlot': 0},
		{'homeSlot': 2, 'awaySlot': 4},
		{'homeSlot': 1, 'awaySlot': 5},
		{'homeSlot': 19, 'awaySlot': 6},
		{'homeSlot': 18, 'awaySlot': 7},
		{'homeSlot': 17, 'awaySlot': 8},
		{'homeSlot': 16, 'awaySlot': 9},
		{'homeSlot': 15, 'awaySlot': 10},
		{'homeSlot': 14, 'awaySlot': 11},
		{'homeSlot': 13, 'awaySlot': 12}
	],
	37: [
		{'homeSlot': 0, 'awaySlot': 2},
		{'homeSlot': 3, 'awaySlot': 1},
		{'homeSlot': 4, 'awaySlot': 19},
		{'homeSlot': 5, 'awaySlot': 18},
		{'homeSlot': 6, 'awaySlot': 17},
		{'homeSlot': 7, 'awaySlot': 16},
		{'homeSlot': 8, 'awaySlot': 15},
		{'homeSlot': 9, 'awaySlot': 14},
		{'homeSlot': 10, 'awaySlot': 13},
		{'homeSlot': 11, 'awaySlot': 12}
	],
	38: [
		{'homeSlot': 1, 'awaySlot': 0},
		{'homeSlot': 19, 'awaySlot': 2},
		{'homeSlot': 18, 'awaySlot': 3},
		{'homeSlot': 17, 'awaySlot': 4},
		{'homeSlot': 16, 'awaySlot': 5},
		{'homeSlot': 15, 'awaySlot': 6},
		{'homeSlot': 14, 'awaySlot': 7},
		{'homeSlot': 13, 'awaySlot': 8},
		{'homeSlot': 12, 'awaySlot': 9},
		{'homeSlot': 11, 'awaySlot': 10}
	]
}

systemKnockoutSchedule = {
	1: [ # Preliminary round
		{'homeSlot: '} # Fixture 1
	]
}